name: Pull request workflow

on:
  pull_request:
    types: [closed, opened]
jobs:
  pull_request_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: github.event =='pull_request' && github.event.action == 'opened'
        with:
          project: TeamPlanning
          column: En cours
          repo-token: ${{ secrets.PROJECT_TOKEN }}